[package]
name = "dynonym"
version = "0.1.0-dev"
authors = ["Tobias Stolzmann <tobias.stolzmann@gmail.com>"]
license = "MIT"
keywords = ["dns", "ddns", "dyndns", "http", "server", "rocket"]
categories = ["network-programming", "web-programming::http-server"]
description = "A minimalistic HTTP server processing DDNS update requests"
readme = "README.md"
documentation = "https://docs.rs/dynonym"
repository = "https://github.com/teiesti/dynonym"

[dependencies]
bcrypt = "0.1"
error-chain = "0.11"
num_cpus = "1"
serde = "1"
serde_derive = "1"
toml = "0.4"

[dev-dependencies]
tempfile = "2"

[[bin]]
name = "dynonym"
doc = false
